server:
  port: 8080
  servlet:


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/garderie_db
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: user
      password: pass
      roles:
      - USER
      - ADMIN
      - VISITOR
      - TUTEUR

application:
  jwt:
    expiresAt: 846_000
    headerPrefix: "Bearer"
    secret: "ciao"
    headerKey: "Authorization"


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create


